#ifndef YACX_TEST_COMPARE_HPP
#define YACX_TEST_COMPARE_HPP
enum compare {
  CORRECT,
  CHECK_COMPARE_WRONG,
  A_COMPARE_WRONG,
  X_COMPARE_WRONG,
  Y_COMPARE_WRONG,
  OUT_COMPARE_WRONG
};
#endif // YACX_TEST_COMPARE_HPP
