#ifndef CUDAEXECUTOR_TEST_COMPARE_HPP
#define CUDAEXECUTOR_TEST_COMPARE_HPP
enum compare {
  CORRECT,
  CHECK_COMPARE_WRONG,
  A_COMPARE_WRONG,
  X_COMPARE_WRONG,
  Y_COMPARE_WRONG,
  OUT_COMPARE_WRONG
};
#endif // CUDAEXECUTOR_TEST_COMPARE_HPP
