/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ArrayArg */

#ifndef _Included_ArrayArg
#define _Included_ArrayArg
#ifdef __cplusplus
extern "C" {
#endif
#undef ArrayArg_FLOAT
#define ArrayArg_FLOAT 1L
#undef ArrayArg_INT
#define ArrayArg_INT 2L
#undef ArrayArg_LONG
#define ArrayArg_LONG 3L
#undef ArrayArg_DOUBLE
#define ArrayArg_DOUBLE 4L
#undef ArrayArg_BOOLEAN
#define ArrayArg_BOOLEAN 5L
/*
 * Class:     ArrayArg
 * Method:    createInternal
 * Signature: ([FZ)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createInternal___3FZ
  (JNIEnv *, jclass, jfloatArray, jboolean);

/*
 * Class:     ArrayArg
 * Method:    createInternal
 * Signature: ([IZ)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createInternal___3IZ
  (JNIEnv *, jclass, jintArray, jboolean);

/*
 * Class:     ArrayArg
 * Method:    createInternal
 * Signature: ([JZ)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createInternal___3JZ
  (JNIEnv *, jclass, jlongArray, jboolean);

/*
 * Class:     ArrayArg
 * Method:    createInternal
 * Signature: ([DZ)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createInternal___3DZ
  (JNIEnv *, jclass, jdoubleArray, jboolean);

/*
 * Class:     ArrayArg
 * Method:    createInternal
 * Signature: ([ZZ)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createInternal___3ZZ
  (JNIEnv *, jclass, jbooleanArray, jboolean);

/*
 * Class:     ArrayArg
 * Method:    createOutputInternal
 * Signature: (J)LArrayArg;
 */
JNIEXPORT jobject JNICALL Java_ArrayArg_createOutputInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ArrayArg
 * Method:    asFloatArrayInternal
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_ArrayArg_asFloatArrayInternal
  (JNIEnv *, jobject);

/*
 * Class:     ArrayArg
 * Method:    asIntArrayInternal
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_ArrayArg_asIntArrayInternal
  (JNIEnv *, jobject);

/*
 * Class:     ArrayArg
 * Method:    asLongArrayInternal
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_ArrayArg_asLongArrayInternal
  (JNIEnv *, jobject);

/*
 * Class:     ArrayArg
 * Method:    asDoubleArrayInternal
 * Signature: ()[D
 */
JNIEXPORT jdoubleArray JNICALL Java_ArrayArg_asDoubleArrayInternal
  (JNIEnv *, jobject);

/*
 * Class:     ArrayArg
 * Method:    asBooleanArrayInternal
 * Signature: ()[Z
 */
JNIEXPORT jbooleanArray JNICALL Java_ArrayArg_asBooleanArrayInternal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
