/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ByteArg */

#ifndef _Included_ByteArg
#define _Included_ByteArg
#ifdef __cplusplus
extern "C" {
#endif
#undef ByteArg_SIZE_BYTES
#define ByteArg_SIZE_BYTES 1L
/*
 * Class:     ByteArg
 * Method:    createValue
 * Signature: (B)LKernelArg;
 */
JNIEXPORT jobject JNICALL Java_ByteArg_createValue
  (JNIEnv *, jclass, jbyte);

/*
 * Class:     ByteArg
 * Method:    createInternal
 * Signature: ([BZ)LByteArg;
 */
JNIEXPORT jobject JNICALL Java_ByteArg_createInternal
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     ByteArg
 * Method:    createOutputInternal
 * Signature: (I)LByteArg;
 */
JNIEXPORT jobject JNICALL Java_ByteArg_createOutputInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     ByteArg
 * Method:    asByteArray
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_ByteArg_asByteArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
