/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Executor */

#ifndef _Included_Executor
#define _Included_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Executor
 * Method:    benchmark
 * Signature: (LKernel;LDevice;[LKernelArg;I)[LKernelTime;
 */
JNIEXPORT jobjectArray JNICALL Java_Executor_benchmark
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
