/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FloatArg */

#ifndef _Included_FloatArg
#define _Included_FloatArg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FloatArg
 * Method:    createInternal
 * Signature: ([FZ)LFloatArg;
 */
JNIEXPORT jobject JNICALL Java_FloatArg_createInternal
  (JNIEnv *, jclass, jfloatArray, jboolean);

/*
 * Class:     FloatArg
 * Method:    createOutputInternal
 * Signature: (I)LFloatArg;
 */
JNIEXPORT jobject JNICALL Java_FloatArg_createOutputInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     FloatArg
 * Method:    asFloatArray
 * Signature: ()[F
 */
JNIEXPORT jfloatArray JNICALL Java_FloatArg_asFloatArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
