/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIHandle */

#ifndef _Included_JNIHandle
#define _Included_JNIHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIHandle
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JNIHandle_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
