/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kernel */

#ifndef _Included_Kernel
#define _Included_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Kernel
 * Method:    compile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kernel_compile
  (JNIEnv *, jobject);

/*
 * Class:     Kernel
 * Method:    configure
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_Kernel_configure
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Kernel
 * Method:    launch
 * Signature: ([LKernelArg;)V
 */
JNIEXPORT void JNICALL Java_Kernel_launch
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     Kernel
 * Method:    build
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Kernel_build
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
