/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class KernelArg */

#ifndef _Included_KernelArg
#define _Included_KernelArg
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
