/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Kernel */

#ifndef _Included_Kernel
#define _Included_Kernel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Kernel
 * Method:    configureInternal
 * Signature: (IIIIII)V
 */
JNIEXPORT void JNICALL Java_Kernel_configureInternal
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jint);

/*
 * Class:     Kernel
 * Method:    launchInternel
 * Signature: ([LKernelArg;)V
 */
JNIEXPORT void JNICALL Java_Kernel_launchInternel
  (JNIEnv *, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
