/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LongArg */

#ifndef _Included_LongArg
#define _Included_LongArg
#ifdef __cplusplus
extern "C" {
#endif
#undef LongArg_SIZE_BYTES
#define LongArg_SIZE_BYTES 8L
/*
 * Class:     LongArg
 * Method:    createValue
 * Signature: (J)LKernelArg;
 */
JNIEXPORT jobject JNICALL Java_LongArg_createValue
  (JNIEnv *, jclass, jlong);

/*
 * Class:     LongArg
 * Method:    create
 * Signature: (LLongArg;Z)LLongArg;
 */
JNIEXPORT jobject JNICALL Java_LongArg_create
  (JNIEnv *, jclass, jobject, jboolean);

/*
 * Class:     LongArg
 * Method:    createInternal
 * Signature: ([JZ)LLongArg;
 */
JNIEXPORT jobject JNICALL Java_LongArg_createInternal
  (JNIEnv *, jclass, jlongArray, jboolean);

/*
 * Class:     LongArg
 * Method:    createOutputInternal
 * Signature: (I)LLongArg;
 */
JNIEXPORT jobject JNICALL Java_LongArg_createOutputInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     LongArg
 * Method:    asLongArray
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_LongArg_asLongArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
