/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Options */

#ifndef _Included_Options
#define _Included_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Options
 * Method:    insert
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Options_insert__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Options
 * Method:    insert
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Options_insert__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
