/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Programm */

#ifndef _Included_Programm
#define _Included_Programm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Programm
 * Method:    create
 * Signature: (Ljava/lang/String;)LProgramm;
 */
JNIEXPORT jobject JNICALL Java_Programm_create
  (JNIEnv *, jclass, jstring);

/*
 * Class:     Programm
 * Method:    kernel
 * Signature: (Ljava/lang/String;)LKernel;
 */
JNIEXPORT jobject JNICALL Java_Programm_kernel
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
