/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Program */

#ifndef _Included_Program
#define _Included_Program
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Program
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;)LProgram;
 */
JNIEXPORT jobject JNICALL Java_Program_create
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     Program
 * Method:    compile
 * Signature: ()LKernel;
 */
JNIEXPORT jobject JNICALL Java_Program_compile
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
