/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ShortArg */

#ifndef _Included_ShortArg
#define _Included_ShortArg
#ifdef __cplusplus
extern "C" {
#endif
#undef ShortArg_SIZE_BYTES
#define ShortArg_SIZE_BYTES 2L
/*
 * Class:     ShortArg
 * Method:    createValue
 * Signature: (S)LKernelArg;
 */
JNIEXPORT jobject JNICALL Java_ShortArg_createValue
  (JNIEnv *, jclass, jshort);

/*
 * Class:     ShortArg
 * Method:    createInternal
 * Signature: ([SZ)LShortArg;
 */
JNIEXPORT jobject JNICALL Java_ShortArg_createInternal
  (JNIEnv *, jclass, jshortArray, jboolean);

/*
 * Class:     ShortArg
 * Method:    createOutputInternal
 * Signature: (I)LShortArg;
 */
JNIEXPORT jobject JNICALL Java_ShortArg_createOutputInternal
  (JNIEnv *, jclass, jint);

/*
 * Class:     ShortArg
 * Method:    asShortArray
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_ShortArg_asShortArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
