/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_ArrayArg */

#ifndef _Included_yacx_ArrayArg
#define _Included_yacx_ArrayArg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_ArrayArg
 * Method:    createOutputInternal
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_yacx_ArrayArg_createOutputInternal
  (JNIEnv *, jclass, jlong);

/*
 * Class:     yacx_ArrayArg
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_yacx_ArrayArg_getSize
  (JNIEnv *, jobject);

/*
 * Class:     yacx_ArrayArg
 * Method:    isDownload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_yacx_ArrayArg_isDownload
  (JNIEnv *, jobject);

/*
 * Class:     yacx_ArrayArg
 * Method:    setDownload
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_yacx_ArrayArg_setDownload
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     yacx_ArrayArg
 * Method:    isUpload
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_yacx_ArrayArg_isUpload
  (JNIEnv *, jobject);

/*
 * Class:     yacx_ArrayArg
 * Method:    setUpload
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_yacx_ArrayArg_setUpload
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     yacx_ArrayArg
 * Method:    sliceInternal
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_yacx_ArrayArg_sliceInternal
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
