/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_Executor */

#ifndef _Included_yacx_Executor
#define _Included_yacx_Executor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_Executor
 * Method:    benchmark
 * Signature: (Lyacx/Kernel;Lyacx/Device;[Lyacx/KernelArg;I)[Lyacx/KernelTime;
 */
JNIEXPORT jobjectArray JNICALL Java_yacx_Executor_benchmark
  (JNIEnv *, jclass, jobject, jobject, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
