/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_ShortArg */

#ifndef _Included_yacx_ShortArg
#define _Included_yacx_ShortArg
#ifdef __cplusplus
extern "C" {
#endif
#undef yacx_ShortArg_SIZE_BYTES
#define yacx_ShortArg_SIZE_BYTES 1LL
/*
 * Class:     yacx_ShortArg
 * Method:    createValue
 * Signature: (S)Lyacx/KernelArg;
 */
JNIEXPORT jobject JNICALL Java_yacx_ShortArg_createValue
  (JNIEnv *, jclass, jshort);

/*
 * Class:     yacx_ShortArg
 * Method:    createInternal
 * Signature: ([SZ)Lyacx/ShortArg;
 */
JNIEXPORT jobject JNICALL Java_yacx_ShortArg_createInternal
  (JNIEnv *, jclass, jshortArray, jboolean);

/*
 * Class:     yacx_ShortArg
 * Method:    asShortArray
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_yacx_ShortArg_asShortArray
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
