/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_Devices */

#ifndef _Included_yacx_Devices
#define _Included_yacx_Devices
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_Devices
 * Method:    findDevice
 * Signature: ()Lyacx/Device;
 */
JNIEXPORT jobject JNICALL Java_yacx_Devices_findDevice__
  (JNIEnv *, jclass);

/*
 * Class:     yacx_Devices
 * Method:    findDevice
 * Signature: (Ljava/lang/String;)Lyacx/Device;
 */
JNIEXPORT jobject JNICALL Java_yacx_Devices_findDevice__Ljava_lang_String_2
  (JNIEnv *, jclass, jstring);

/*
 * Class:     yacx_Devices
 * Method:    findDeviceByUUID
 * Signature: (Ljava/lang/String;)Lyacx/Device;
 */
JNIEXPORT jobject JNICALL Java_yacx_Devices_findDeviceByUUID
  (JNIEnv *, jclass, jstring);

/*
 * Class:     yacx_Devices
 * Method:    findDevices
 * Signature: ()[Lyacx/Device;
 */
JNIEXPORT jobjectArray JNICALL Java_yacx_Devices_findDevices
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
