/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_Options */

#ifndef _Included_yacx_Options
#define _Included_yacx_Options
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_Options
 * Method:    createOptions
 * Signature: ()Lyacx/Options;
 */
JNIEXPORT jobject JNICALL Java_yacx_Options_createOptions
  (JNIEnv *, jclass);

/*
 * Class:     yacx_Options
 * Method:    insertInternal
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yacx_Options_insertInternal__Ljava_lang_String_2
  (JNIEnv *, jobject, jstring);

/*
 * Class:     yacx_Options
 * Method:    insertInternal
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_yacx_Options_insertInternal__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     yacx_Options
 * Method:    getSize
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_yacx_Options_getSize
  (JNIEnv *, jobject);

/*
 * Class:     yacx_Options
 * Method:    getOptions
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_yacx_Options_getOptions
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
