/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_PaddingArg */

#ifndef _Included_yacx_PaddingArg
#define _Included_yacx_PaddingArg
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_PaddingArg
 * Method:    createMatrixPaddingInternal
 * Signature: (Lyacx/ArrayArg;IIIIII)Lyacx/PaddingArg;
 */
JNIEXPORT jobject JNICALL Java_yacx_PaddingArg_createMatrixPaddingInternal
  (JNIEnv *, jclass, jobject, jint, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
