/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class yacx_JNIHandle */

#ifndef _Included_yacx_JNIHandle
#define _Included_yacx_JNIHandle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     yacx_JNIHandle
 * Method:    dispose
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_yacx_JNIHandle_dispose
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
